CREATE DATABASE treedom;
USE treedom;
CREATE TABLE usuario (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100),
email VARCHAR(100),
senha VARCHAR(100)
);
CREATE TABLE cards (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100),
raridade VARCHAR(100),
img VARCHAR(200)
);
CREATE TABLE user_cards (
id INT AUTO_INCREMENT PRIMARY KEY,
id_user VARCHAR(100),
id_card VARCHAR(100)
);